import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import LinkValidator from "../components/LinkValidator";

export default function Home() {
  const [inputName, setInputName] = useState("");

  const name = () => {
    const inputN = document.getElementById("inputName");
    setInputName(inputN.value);
  };

  return (
    <div>
      <Head>
        <title>Economapas Quiz</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <section className="center flexCenter">
          <div className={styles.cardContent}>
            <h1 className={styles.title}>Insira seu nome:</h1>
            <form className={styles.form}>
              <input
                type="text"
                id="inputName"
                placeholder="Insira seu nome"
                className={styles.input}
                onChange={name}
                onSubmit={(e) => e.preventDefault()}
              />
              <button>
                <LinkValidator name={inputName} />
              </button>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
}
