import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useContext, useEffect } from "react";
import MyContext from '../contexts/myContext';
import LinkValidator from "../components/LinkValidator";

export default function Home() {
  const { name, setName, setAllMyAnswers, setCorrectAnswers } = useContext(MyContext)

  useEffect(() => {
    setAllMyAnswers("")
    setCorrectAnswers(0)
  }, []);

  const changeName = () => {
    const inputN = document.getElementById("inputName");
    setName(inputN.value);
  };

  return (
    <div>
      <Head>
        <title>Economapas Quiz</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <section className="center flexCenter">
          <div className={styles.cardContent}>
            <h1 className={styles.title}>Insira seu nome:</h1>
            <form className={styles.form}>
              <input
                type="text"
                id="inputName"
                placeholder="Insira seu nome"
                className={styles.input}
                onChange={changeName}
                onSubmit={(e) => e.preventDefault()}
              />
              <button>
                <LinkValidator name={name} />
              </button>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
}
