import React from "react";
import Head from "next/head";
import { useContext, useEffect } from "react";
import MyContext from '../contexts/myContext';
import LinkValidator from "../components/LinkValidator";

export default function Home() {
  const { name, setName, setAllMyAnswers, setAllCorrectAnswers } = useContext(MyContext)

  useEffect(() => {
    setAllMyAnswers("")
    setAllCorrectAnswers(0)
  }, []);

  const changeName = () => {
    const inputN = document.getElementById("inputName");
    setName(inputN.value);
  };

  return (
    <div>
      <Head>
        <title>Economapas Quiz</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <section className="translate absolute top-1/2 left-1/2 flex justify-center items-center">
          <div className="bg-white rounded p-8 text-center">
            <h1 className="font-highlight text-2xl">Insira seu nome:</h1>
            <form className="text-center">
              <input
                type="text"
                id="inputName"
                placeholder="Insira seu nome"
                className="p-2 block mb-4 ml-0"
                onChange={changeName}
                onSubmit={(e) => e.preventDefault()}
              />
              <button>
                <LinkValidator name={name} />
              </button>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
}
